run:
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - configs

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: false

issues:
  exclude-rules:
    # SA1029 – Inappropriate key in call to context.WithValue
    # https://staticcheck.io/docs/checks#SA1029
    - linters:
        - staticcheck
      text: "SA1029:"
