version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - goconst
    - lll
    - misspell
    - unconvert
    - unparam
  settings:
    errcheck:
      check-blank: true
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
    unparam:
      check-exported: false
    staticcheck:
      checks:
        - all
        - '-SA1029'
        - '-SA1019'
        - '-ST1003'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - configs
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - configs
      - third_party$
      - builtin$
      - examples$
