preset: "angular"

branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/exec"
    - "prepareCmd": "sed -i -e 's/\\(Version.*\\)\"\\(.*\\)\"/\\1\"${nextRelease.version}\"/' pkg/version/version*"
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - pkg/version/**/*
      message: |-
        chore: Bump to version ${nextRelease.version} [skip ci]
  - - "@semantic-release/github"
    - successComment: false
      failComment: false
      labels: false
      releasedLabels: false
