version: '3.7'

services:
  sdk:
    build:
      context: .
      target: builder
    image: microservices/sdk/go-sdk
    environment:
      APP_ENV: test
      APP_ROOT: /sdk
    volumes:
      - .:/sdk
    security_opt:
      - seccomp:unconfined
