name: CI

on: push

env:
  DOCKER_CACHE_PATH: ${{ github.workspace }}/tmp/docker-cache
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        # A GitHub Action to expose the slug values of some GitHub ENV variables
        # https://github.com/rlespinasse/github-slug-action
        uses: rlespinasse/github-slug-action@v3.x

      - uses: docker/build-push-action@v2
        # GitHub Action to build and push Docker images with Buildx
        # https://github.com/docker/build-push-action
        name: Build image
        with:
          push: false
          target: builder
          tags: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}

  check:
    name: check
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        # A GitHub Action to expose the slug values of some GitHub ENV variables
        # https://github.com/rlespinasse/github-slug-action
        uses: rlespinasse/github-slug-action@v3.x

      - uses: docker/build-push-action@v2
        # GitHub Action to build and push Docker images with Buildx
        # https://github.com/docker/build-push-action
        name: Build image
        with:
          push: false
          target: builder
          tags: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}

      - uses: addnab/docker-run-action@v2
        # Run an image built by a previous step.
        # https://github.com/addnab/docker-run-action
        # https://github.com/marketplace/actions/docker-run-action
        name: Check format
        with:
          image: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}
          run: mage fmt:check

      - uses: addnab/docker-run-action@v2
        # Run an image built by a previous step.
        # https://github.com/addnab/docker-run-action
        # https://github.com/marketplace/actions/docker-run-action
        name: Run linter
        env:
          CI_GOLANGCI_LINT_VERSION: "1.20.1"
        with:
          image: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}
          run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v${{ env.CI_GOLANGCI_LINT_VERSION }} && mage fmt:lint

  test:
    name: test
    needs: [build, check]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        # A GitHub Action to expose the slug values of some GitHub ENV variables
        # https://github.com/rlespinasse/github-slug-action
        uses: rlespinasse/github-slug-action@v3.x


      - uses: docker/build-push-action@v2
        # GitHub Action to build and push Docker images with Buildx
        # https://github.com/docker/build-push-action
        name: Build image
        with:
          push: false
          target: builder
          tags: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}

      - uses: addnab/docker-run-action@v2
        # Run an image built by a previous step.
        # https://github.com/addnab/docker-run-action
        # https://github.com/marketplace/actions/docker-run-action
        name: Run tests
        with:
          image: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}
          run: mage test:run

  notify:
    name: notify:slack
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: scribdbot
      SLACK_CHANNEL: '#service-foundations-release'
      SLACK_ICON: 'https://github.com/scribdbot.png?size=48'
      SLACK_FOOTER: ""
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2.1.0
        if: failure()
        env:
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: Build of commit <https://github.com/scribd/go-sdk/commit/${{ github.sha }}|${{ env.GITHUB_SHA_SHORT }}> on `main` branch of <https://github.com/${{ github.repository }}|${{ github.repository }}> failed.

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2.1.0
        if: success()
        env:
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: Build of commit <https://github.com/scribd/go-sdk/commit/${{ github.sha }}|${{ env.GITHUB_SHA_SHORT }}> on `main` branch of <https://github.com/${{ github.repository }}|${{ github.repository }}> succeeded.
