name: Release

on: workflow_dispatch

env:
  AWS_REGION: us-east-2
  DOCKER_BUILDKIT: 1
  DOCKER_CACHE_PATH: ${{ github.workspace }}/tmp/docker-cache

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
           persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@13.0.0
            @semantic-release/release-notes-generator@14.0.1
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@10.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.SCRIBD_GITHUB_RELEASE_TOKEN }}

      - name: Send Slack notification
        if: always()
        uses: scribd/job-notification@v1.3.0
        with:
          token: ${{ secrets.SCRIBD_SLACK_GENERIC_TOKEN_PUBLIC }}
          channel: service-foundations-release
