name: Velocity Workflow
on:
  pull_request:
    types: [opened, closed]
jobs:
  metrics:
    if: |
      (github.event.action == 'closed' &&
      github.event.pull_request.merged == true) ||
      github.event.action == 'opened'
    name: Track merge request activity
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: tspascoal/get-user-teams-membership@v1
        id: actorTeams
        with:
          username: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}

      - id: datadog-metrics
        uses: scribd/github-action-datadog-reporting@v1
        with:
          datadog-metric-prefix: 'github.action'
          metrics-type: 'velocity'
          teams: ${{ steps.actorTeams.outputs.teams }}
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          OCTOKIT_TOKEN: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}
